More integrity

diff --git a/bin/util/install-dependencies b/bin/util/install-dependencies
--- a/bin/util/install-dependencies
+++ b/bin/util/install-dependencies
@@ -2,16 +2,50 @@
 
 if hash cpanm >/dev/null 2>&1
 then
-    cat cpan.dependencies | cpanm
-else
-    cat >&2 <<message
-All of the dependencies are in (cpan.dependencies)
+    have_cpanm=1
+fi
 
-You can install them however you'd like, but I'd highly
-recommend installing 'cpanm' first and rerunning this script.
+while read dependency
+do
+    perl -e "use $dependency" 2>/dev/null
 
-https://github.com/miyagawa/cpanminus
-message
+    if [ $? != 0 ]
+    then
+        if [ $have_cpanm ]
+        then
+            cpanm $dependency
+        else
+            cpan $dependency
+        fi
 
+        perl -e "use $dependency" 2>/dev/null
+
+        if [ $? != 0 ]
+        then
+            echo "Module installation failed ($dependency)" >&2
+            exit 1
+        fi
+    fi
+done < cpan.dependencies
+
+if ! hash Rscript >/dev/null 2>&1
+then
+    "Please install R: http://cran.r-project.org/" >&2
     exit 1
 fi
+
+if ! hash cc >/dev/null 2>&1
+then
+    cat >&2 <<message
+I need to be able to call a C compiler with the command (cc)
+
+If you already have a C compiler installed, please create a
+link to it from "cc".
+
+If you don't already have a C compiler installed, please
+install one.
+message
+    exit 1
+fi
+
+prove t/integration/install-dependencies.t
